version: "3.9"
name: lf-services
services:
  redis:
    container_name: leet_fleet_redis
    image: redis/redis-stack:latest
    ports:
      # Redis
      - 6379:6379
      # Redis Insight
      - 8001:8001
    volumes:
      # Following is redis-stack config file. Using it creates unexpected behaviour
      #- ./_the_cloud/_redis_config/redis.conf:/redis-stack.conf
      - ./_the_cloud/_redis_logs/:/logs
      - ./_the_cloud/:/leetfleet
    environment:
      # Logging (debug / verbose / notice / warning ):
      #  -> loglevel notice
      # By default Redis will save the DB:
      #   * After 3600 seconds (an hour) if at least 1 change was performed
      #   * After 300 seconds (5 minutes) if at least 100 changes were performed
      #   * After 60 seconds if at least 10000 changes were performed
      # You can set these explicitly:
      #  -> save 3600 1 300 100 60 10000
      - REDIS_ARGS=--logfile /logs/redis-stack.log --dbfilename leetfleet.rdb --dir /leetfleet
  # core:
  #   build: core
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - redis
  # client:
  #   image: "client:latest"
  #   depends_on:
  #     - "wish_I_knew"

